lstm2

과정 요약:<br> 
feature: season, day of week, week number, sales <br> 
feature engineering: normalize+ denormalize

결과요약: seed 7: rmse 96.04 (마지막 

상세과정:
주중(1)/주말(2) + 겨울(1)봄(2)여름(3)가을(4) // 
이미 lstm이라는 것이 sequence 개념이 있으므로 시간축(1~397)를 feature로 설정하는 것은 의미가 없을 듯 하여 LSTM 시도2에서는 제외함

추가의견) 개인적으로 이상점을 제거한 후 normalize를 하면 rmse가 커질 수 밖에 없다고 생각함. 다음시도(lstm3)은 이상점을 제거하지 않고 normalize를 하고, lstm4에서는 이상점을 제거하고 normalize를 하지 않는 것을 시도하겠다.

추가의견2) 처음에는 denormalize과정 없이 rmse를 구했는데, 이것보다는 denormalize를 한 후 rmse를 구하여 모델간 비교를 하는 것이 더 적절한 것 같다. normalize는 어디까지나 변환이니 항상 변환을 할때는 역변환을 하여 원본 데이터 형태m로 생각하는 것이 덜 헷갈리고, 결과값에 대한 더욱 직관적인 이해가 가능할 것 같다. 그리고, 여러 형태의 data transformation이 있는데 normalize 가장 마지막 단계의 data transformation인 것 같다. 다른 로그나 루트 변환을 한 후 normalization을 하고, 그리고 예측값이 모델을 통해 생성되면 바로 denormalize하고...예측(뉴럴) 모델의 input직전과 output직후.

In [1]:
import tensorflow as tf
import numpy as np
import matplotlib
import os
import matplotlib.pyplot as plt
import pandas as pd
from datetime import datetime   

set seednumber(7 or 77)

In [2]:
tf.set_random_seed(7)

# 1. DATA 준비

In [3]:
columns=['date','sales']

txs=pd.read_table('./lstmData/lstmPrac2.csv', sep=',',header=None,names=columns )
txs.info()
txs.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 397 entries, 0 to 396
Data columns (total 2 columns):
date     397 non-null object
sales    397 non-null int64
dtypes: int64(1), object(1)
memory usage: 6.3+ KB


date  sales
0  2016-01-01     34
1  2016-01-02     41
2  2016-01-03     54
3  2016-01-04     41
4  2016-01-05     35

In [4]:
sales=list(np.log(txs['sales']))

c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


In [5]:
sales

[3.5263605246161616,
 3.713572066704308,
 3.9889840465642745,
 3.713572066704308,
 3.5553480614894135,
 3.784189633918261,
 3.912023005428146,
 3.7376696182833684,
 3.7376696182833684,
 4.1896547420264252,
 3.912023005428146,
 4.0073331852324712,
 4.0253516907351496,
 3.970291913552122,
 3.784189633918261,
 3.9889840465642745,
 3.9889840465642745,
 3.912023005428146,
 3.6888794541139363,
 3.8918202981106265,
 3.3322045101752038,
 4.2766661190160553,
 4.2626798770413155,
 3.970291913552122,
 3.7612001156935624,
 3.6375861597263857,
 4.0073331852324712,
 3.8918202981106265,
 3.7612001156935624,
 3.8918202981106265,
 3.8918202981106265,
 3.784189633918261,
 3.6635616461296463,
 3.9512437185814275,
 3.8066624897703196,
 3.4965075614664802,
 3.7612001156935624,
 3.6888794541139363,
 3.8286413964890951,
 3.8918202981106265,
 3.912023005428146,
 3.6109179126442243,
 3.6109179126442243,
 3.8066624897703196,
 3.8712010109078911,
 3.8712010109078911,
 3.6375861597263857,
 4.0943445622221004,
 3.

## 1.1 기본 feature

'ds-y'의 ds로부터 api로 얻을 수 있는 값

year, day of week, month, week number를 기본 feature로 설정

In [6]:
year = lambda x: datetime.strptime(x, "%Y-%m-%d" ).year  
day_of_week = lambda x: datetime.strptime(x, "%Y-%m-%d" ).weekday()
month = lambda x: datetime.strptime(x, "%Y-%m-%d" ).month
# please read docs on how week numbers are calculate
week_number = lambda x: datetime.strptime(x, "%Y-%m-%d" ).strftime('%V')

In [7]:
txs['year'] = txs['date'].map(year)
txs['month']=txs['date'].map(month)
txs['week_number']=txs['date'].map(week_number)
txs['day_of_week']=txs['date'].map(day_of_week)

## 1.2 추가 feature + 가공

'ds-y'의 ds로부터 api로 얻을 수 없는 값: 본 feature를 가공한 feature + ds와 무관한 feature

### X

계절

In [8]:
seasons = [0,0,1,1,1,2,2,2,3,3,3,0] #dec - feb is winter, then spring, summer, fall etc
season = lambda x: seasons[(datetime.strptime(x, "%Y-%m-%d" ).month-1)]

주중/주말(0,1)

In [9]:
day_of_week01s=[0,0,0,0,0,1,1]
day_of_week01= lambda x: day_of_week01s[(datetime.strptime(x, "%Y-%m-%d" ).weekday())]

In [10]:
txs['season']=txs['date'].map(season)
txs['day_of_week01']=txs['date'].map(day_of_week01)
txs

date  sales  year  month week_number  day_of_week  season  \
0    2016-01-01     34  2016      1          53            4       0   
1    2016-01-02     41  2016      1          53            5       0   
2    2016-01-03     54  2016      1          53            6       0   
3    2016-01-04     41  2016      1          01            0       0   
4    2016-01-05     35  2016      1          01            1       0   
5    2016-01-06     44  2016      1          01            2       0   
6    2016-01-07     50  2016      1          01            3       0   
7    2016-01-08     42  2016      1          01            4       0   
8    2016-01-09     42  2016      1          01            5       0   
9    2016-01-10     66  2016      1          01            6       0   
10   2016-01-11     50  2016      1          02            0       0   
11   2016-01-12     55  2016      1          02            1       0   
12   2016-01-13     56  2016      1          02            2       0   
13   2016-01-14     53  2016      1          02            3       0   
14   2016-01-15     44  2016      1          02            4       0   
15   2016-01-16     54  2016      1          02            5       0   
16   2016-01-17     54  2016      1          02            6       0   
17   2016-01-18     50  2016      1          03            0       0   
18   2016-01-19     40  2016      1          03            1       0   
19   2016-01-20     49  2016      1          03            2       0   
20   2016-01-21     28  2016      1          03            3       0   
21   2016-01-22     72  2016      1          03            4       0   
22   2016-01-23     71  2016      1          03            5       0   
23   2016-01-24     53  2016      1          03            6       0   
24   2016-01-25     43  2016      1          04            0       0   
25   2016-01-26     38  2016      1          04            1       0   
26   2016-01-27     55  2016      1          04            2       0   
27   2016-01-28     49  2016      1          04            3       0   
28   2016-01-29     43  2016      1          04            4       0   
29   2016-01-30     49  2016      1          04            5       0   
..          ...    ...   ...    ...         ...          ...     ...   
367  2017-01-02     16  2017      1          01            0       0   
368  2017-01-03     20  2017      1          01            1       0   
369  2017-01-04     12  2017      1          01            2       0   
370  2017-01-05     11  2017      1          01            3       0   
371  2017-01-06     22  2017      1          01            4       0   
372  2017-01-07     20  2017      1          01            5       0   
373  2017-01-08     16  2017      1          01            6       0   
374  2017-01-09     17  2017      1          02            0       0   
375  2017-01-10     97  2017      1          02            1       0   
376  2017-01-11      0  2017      1          02            2       0   
377  2017-01-12     23  2017      1          02            3       0   
378  2017-01-13    100  2017      1          02            4       0   
379  2017-01-14     18  2017      1          02            5       0   
380  2017-01-15     13  2017      1          02            6       0   
381  2017-01-16     21  2017      1          03            0       0   
382  2017-01-17     24  2017      1          03            1       0   
383  2017-01-18     16  2017      1          03            2       0   
384  2017-01-19     18  2017      1          03            3       0   
385  2017-01-20     22  2017      1          03            4       0   
386  2017-01-21     18  2017      1          03            5       0   
387  2017-01-22     11  2017      1          03            6       0   
388  2017-01-23     24  2017      1          04            0       0   
389  2017-01-24     22  2017      1          04            1       0   
390  2017-01-25     20  2017      1          04    

pandas를 통해 구한 각 feature는 list()로 우리의 기준type인 list로 변경이 가능

## 1.3 추가 가공

### 1.3.1 y의 추가 가공

마지막rmse를 계산할 때 원본 데이터를 복원하기 위해 저장해놓음(아무런 가공되지 않은 원본 sales)

In [11]:
originalSales=list(txs['sales'])
sales=list(txs['sales'])

In [12]:
282 in originalSales

True

가공을 하는 순서도 중요한데, 이상점 제거-> log or sqrt -> normalization이다. 

이상점 제거, bucketization 을 하여 새로운 열을 생성하는 방향으로

#### 이상점 제거

이상점 제거를 위해 평균과 표준편차를 구한다. 이상점의 기준은 일단 평균+-2*sd로 설정

In [13]:
def noOutlierSales(sales):
    mean=np.mean(sales)
    std=np.std(sales)
    for i in range(len(sales)):
        if (sales[i]<mean-2*std or sales[i]>mean+2*std):
             sales[i]=int(mean)
    return sales

#### log(y)

In [14]:
def logSales(sales):
    for i in range(len(sales)):
        if sales[i] is 0:
            sales[i]=1
    return np.log(sales)

#### sqrt(y)

In [15]:
def sqrtSales(sales):
    return np.sqrt(sales)

In [16]:
# sales=noOutlierSales(sales)

In [17]:
282 in sales

True

In [18]:
282 in originalSales

True

### 1.3.2 x의 추가 가공

## 1.4 합친 후 (필요 시 normalize하여) 최종 data 생성: XY

계절(0~3) + 요일(0~6) + 주수(1~53) -> 판매량

In [19]:
tempxy=[list(txs['season']),list(txs['day_of_week']),list(txs['week_number']),sales]

계절(0~3) + 요일(0,1) + 주수(1~53) -> 판매량

In [20]:
# tempxy=[list(txs['season']),list(txs['day_of_week01']),list(txs['week_number']),sales]

In [21]:
xy=np.array(tempxy).transpose().astype(np.float)
originalXY=np.array(tempxy).transpose().astype(np.float)

#### Normalization

In [22]:
def minMaxNormalizer(data):
    numerator=data-np.min(data)
    denominator=np.max(data)-np.min(data)
    return numerator/(denominator+1e-7)

Normalization이 필요한 열을 normalize시킴(현재는 sales에 해당하는 마지막 열만 normalize)

In [23]:
xy=minMaxNormalizer(xy)

In [24]:
xy

array([[ 0.        ,  0.00701754,  0.09298246,  0.05964912],
       [ 0.        ,  0.00877193,  0.09298246,  0.07192982],
       [ 0.        ,  0.01052632,  0.09298246,  0.09473684],
       ..., 
       [ 0.        ,  0.01052632,  0.00701754,  0.        ],
       [ 0.        ,  0.        ,  0.00877193,  0.00877193],
       [ 0.        ,  0.00175439,  0.00877193,  0.05438596]])

In [25]:
# xy[:,-1]=minMaxNormalizer(xy[:,-1])

다른 열 ex) XY[:,-3]=minMaxNormalizer(XY[:,-3])

#### Denormalization

예측모델을 통해 얻은 sales결과를 denormalize시켜 기존 단위로 변환

In [26]:
def minMaxDeNormalizer(data, originalData):
    shift=np.min(originalData)
    multiplier=np.max(originalData)-np.min(originalData)
    return (data+shift)*multiplier 

이 함수를 마지막 rmse구하기 전에 호출

# 2. MODEL 설계

## 2.1 사용 model 정의: RNN LSTM

## 2.2 해당 model의 train parameters 설정

In [27]:
#data_dim은 y값 도출을 위한 feature 가지수+1(독립변수 가지수 +1(y포함))
data_dim=4

#data_dim크기의 data 한 묶음이 seq_length만큼 input으로 들어가
seq_length=5

#output_dim(=forecastDays)만큼의 다음날 y_data를 예측
forecastDays=7
output_dim=forecastDays

#hidden_dim은 정말 임의로 설정
hidden_dim=10

#learning rate은 배우는 속도(너무 크지도, 작지도 않게 설정)
learning_rate=0.01

#iterations는 반복 횟수
iterations=1000

## 2.3 사용 model, train parameter에 맞추어 dataset(XY) 변환: dataX, dataY

In [45]:
x=xy
y=xy[:,[-1]]

#build a series dataset(seq_length에 해당하는 전날 X와 다음 forecastDays에 해당하는 Y)
dataX=[]
dataY=[]
for i in range(0, len(y)-seq_length-forecastDays):
    _x=x[i:i+seq_length]
    _y=y[i+seq_length:i+seq_length+forecastDays]
    _y=np.reshape(_y,(forecastDays))
    #     _y=Y[i+seq_length:i+seq_length+forecastDays]
    print(_x,"->",_y)
    dataX.append(_x)
    dataY.append(_y)

[[ 0.          0.00701754  0.09298246  0.05964912]
 [ 0.          0.00877193  0.09298246  0.07192982]
 [ 0.          0.01052632  0.09298246  0.09473684]
 [ 0.          0.          0.00175439  0.07192982]
 [ 0.          0.00175439  0.00175439  0.06140351]] -> [ 0.07719298  0.0877193   0.07368421  0.07368421  0.11578947  0.0877193
  0.09649123]
[[ 0.          0.00877193  0.09298246  0.07192982]
 [ 0.          0.01052632  0.09298246  0.09473684]
 [ 0.          0.          0.00175439  0.07192982]
 [ 0.          0.00175439  0.00175439  0.06140351]
 [ 0.          0.00350877  0.00175439  0.07719298]] -> [ 0.0877193   0.07368421  0.07368421  0.11578947  0.0877193   0.09649123
  0.09824561]
[[ 0.          0.01052632  0.09298246  0.09473684]
 [ 0.          0.          0.00175439  0.07192982]
 [ 0.          0.00175439  0.00175439  0.06140351]
 [ 0.          0.00350877  0.00175439  0.07719298]
 [ 0.          0.00526316  0.00175439  0.0877193 ]] -> [ 0.07368421  0.07368421  0.11578947  0.0877193   

 [ 0.          0.00877193  0.01052632  0.07894737]] -> [ 0.08421053  0.08421053  0.06666667  0.10526316  0.05438596  0.06140351
  0.09298246]
[[ 0.          0.00350877  0.01052632  0.0877193 ]
 [ 0.          0.00526316  0.01052632  0.06491228]
 [ 0.          0.00701754  0.01052632  0.06491228]
 [ 0.          0.00877193  0.01052632  0.07894737]
 [ 0.          0.01052632  0.01052632  0.08421053]] -> [ 0.08421053  0.06666667  0.10526316  0.05438596  0.06140351  0.09298246
  0.12280702]
[[ 0.          0.00526316  0.01052632  0.06491228]
 [ 0.          0.00701754  0.01052632  0.06491228]
 [ 0.          0.00877193  0.01052632  0.07894737]
 [ 0.          0.01052632  0.01052632  0.08421053]
 [ 0.          0.          0.0122807   0.08421053]] -> [ 0.06666667  0.10526316  0.05438596  0.06140351  0.09298246  0.12280702
  0.10877193]
[[ 0.          0.00701754  0.01052632  0.06491228]
 [ 0.          0.00877193  0.01052632  0.07894737]
 [ 0.          0.01052632  0.01052632  0.08421053]
 [ 0.        

## 2.4 train/test split

In [29]:
train_size = int(len(dataY) * 0.7)
test_size = len(dataY) - train_size
trainX, testX = np.array(dataX[0:train_size]), np.array(dataX[train_size:])
trainY, testY = np.array(dataY[0:train_size]), np.array(dataY[train_size:])

## 2.5 input place holders

X의 경우 input type과 [batch size, sequence length, input data dimension(feature+1))]

Y의 경우 input type과 [batch size, 원하는 output 의 개수(forecastDays)]

In [30]:
X=tf.placeholder(tf.float32, [None, seq_length, data_dim])
Y=tf.placeholder(tf.float32, [None, forecastDays])

## 2.6 build LSTM network model

lstm network의 

    기본단위 cell, 
    
    사용 driver, 
    
    예측 y 산출방식, 
    
    loss 함수, 
    
    사용 optimizer 정하기

### lstm의 한 기본단위인 cell을 생성

cell의 결과값을 fully connected layer로 한 번 더 가공할 것이기 때문에 cell의 output dimension인 num_units=hidden_dim로 설정

In [31]:
# cell = tf.contrib.rnn.BasicLSTMCell(num_units=hidden_dim, state_is_tuple=True, activation=tf.tanh)

In [32]:
cell = tf.contrib.rnn.BasicLSTMCell(num_units=hidden_dim, state_is_tuple=True, activation=tf.nn.relu)

### Dynamic rnn이라는 driver를 가동

tf.dynamic_rnn의 input은 cell, input, input type

tf.dynamic_rnn의 output은 outputs와 states

In [33]:
outputs, _states = tf.nn.dynamic_rnn(cell, X, dtype=tf.float32)

### 마지막 cell의 output과 fully connected layer를  이용하여 Y_pred 도출

outputs[:, -1]: cell의 outputs 중 마지막 하나만 이용(we use the last cell's output)

output_dim: fully connected의 최종출력개수는 output_dim(=forecastDays) 

activation_fn= None: 분류 문제가 아니라 회귀 문제이므로 activation_fn은 none

In [34]:
Y_pred = tf.contrib.layers.fully_connected(outputs[:, -1], output_dim, activation_fn= None) 

### loss 정의

In [35]:
loss = tf.reduce_sum(tf.square(Y_pred - Y))  # sum of the squares

### optimizer정의

In [36]:
optimizer = tf.train.AdamOptimizer(learning_rate)

### loss를 줄이는 방향으로 train

In [37]:
train = optimizer.minimize(loss)

In [38]:
xy

array([[ 0.        ,  0.00701754,  0.09298246,  0.05964912],
       [ 0.        ,  0.00877193,  0.09298246,  0.07192982],
       [ 0.        ,  0.01052632,  0.09298246,  0.09473684],
       ..., 
       [ 0.        ,  0.01052632,  0.00701754,  0.        ],
       [ 0.        ,  0.        ,  0.00877193,  0.00877193],
       [ 0.        ,  0.00175439,  0.00877193,  0.05438596]])

In [39]:
originalSales

[34,
 41,
 54,
 41,
 35,
 44,
 50,
 42,
 42,
 66,
 50,
 55,
 56,
 53,
 44,
 54,
 54,
 50,
 40,
 49,
 28,
 72,
 71,
 53,
 43,
 38,
 55,
 49,
 43,
 49,
 49,
 44,
 39,
 52,
 45,
 33,
 43,
 40,
 46,
 49,
 50,
 37,
 37,
 45,
 48,
 48,
 38,
 60,
 31,
 35,
 53,
 70,
 62,
 48,
 51,
 49,
 38,
 32,
 39,
 35,
 30,
 36,
 31,
 31,
 44,
 41,
 41,
 45,
 46,
 45,
 41,
 47,
 48,
 40,
 42,
 38,
 38,
 45,
 48,
 62,
 46,
 38,
 62,
 81,
 40,
 45,
 42,
 53,
 53,
 56,
 53,
 47,
 61,
 64,
 62,
 37,
 65,
 54,
 44,
 46,
 50,
 43,
 53,
 63,
 52,
 2,
 0,
 0,
 72,
 59,
 75,
 47,
 44,
 77,
 90,
 93,
 47,
 61,
 77,
 282,
 50,
 58,
 33,
 41,
 36,
 64,
 49,
 53,
 60,
 43,
 41,
 55,
 45,
 18,
 60,
 69,
 54,
 39,
 50,
 44,
 54,
 57,
 82,
 57,
 44,
 56,
 51,
 55,
 28,
 56,
 54,
 36,
 12,
 25,
 41,
 11,
 6,
 9,
 230,
 29,
 24,
 23,
 14,
 21,
 20,
 25,
 23,
 27,
 31,
 16,
 14,
 30,
 32,
 75,
 35,
 26,
 12,
 21,
 23,
 28,
 25,
 31,
 21,
 17,
 10,
 29,
 34,
 28,
 20,
 36,
 23,
 15,
 42,
 28,
 24,
 29,
 20,
 14,
 18,
 27,
 22

# 3. Model 평가 with RMSE

In [40]:
denormalizedTestY=originalSales[train_size+seq_length:]
# denormalizedTestY_original=sales[train_size+seq_length:]
denormalizedTestY_feed=np.array([[i] for i in denormalizedTestY])

In [41]:
121 in denormalizedTestY

True

In [42]:
targets = tf.placeholder(tf.float32, [None, 1])
predictions = tf.placeholder(tf.float32, [None, 1])
rmse = tf.sqrt(tf.reduce_mean(tf.square(targets - predictions)))

In [43]:
def rootMeanSquaredError(a,b):
    sum=0
    for i in range(len(a)):
        sum=sum+(a[i]-b[i])**2
    return np.sqrt( sum/len(a))

## 2.5 Train and Test

In [44]:
with tf.Session() as sess:
    #초기화
    init = tf.global_variables_initializer()
    sess.run(init)

    # Training step
    for i in range(iterations):
        _, step_loss = sess.run([train, loss], feed_dict={X: trainX, Y: trainY})
        print("[step: {}] loss: {}".format(i, step_loss))

    # Test step
    test_predict = minMaxDeNormalizer(sess.run(Y_pred, feed_dict={X: testX}),originalXY)
#     rmse_val = sess.run(rmse, feed_dict={targets: denormalizedTestY_feed, predictions: test_predict})
#     print("RMSE: {}".format(rmse_val))

    # Plot predictions
    plt.plot(denormalizedTestY_feed) #실제 sales 파란색
    plt.plot(test_predict)           #예측 sales 주황색
    plt.xlabel("Time Period")
    plt.ylabel("Stock Price")
    plt.show()

InternalError: Blas GEMM launch failed : a.shape=(269, 14), b.shape=(14, 40), m=269, n=40, k=14
	 [[Node: rnn/while/rnn/basic_lstm_cell/basic_lstm_cell/MatMul = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/gpu:0"](rnn/while/rnn/basic_lstm_cell/basic_lstm_cell/concat, rnn/while/rnn/basic_lstm_cell/basic_lstm_cell/MatMul/Enter)]]
	 [[Node: Sum/_5 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_800_Sum", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op 'rnn/while/rnn/basic_lstm_cell/basic_lstm_cell/MatMul', defined at:
  File "c:\users\user\anaconda3\envs\tensorflow\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\user\anaconda3\envs\tensorflow\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\ipykernel\kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\zmq\eventloop\ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\tornado\ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\zmq\eventloop\zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\zmq\eventloop\zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\zmq\eventloop\zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\ipykernel\kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\ipykernel\ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\ipykernel\zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\IPython\core\interactiveshell.py", line 2698, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\IPython\core\interactiveshell.py", line 2802, in run_ast_nodes
    if self.run_code(code, result):
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\IPython\core\interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-33-9fe507496544>", line 1, in <module>
    outputs, _states = tf.nn.dynamic_rnn(cell, X, dtype=tf.float32)
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\rnn.py", line 574, in dynamic_rnn
    dtype=dtype)
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\rnn.py", line 737, in _dynamic_rnn_loop
    swap_memory=swap_memory)
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2770, in while_loop
    result = context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2599, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2549, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\rnn.py", line 722, in _time_step
    (output, new_state) = call_cell()
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\rnn.py", line 708, in <lambda>
    call_cell = lambda: cell(input_t, state)
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\rnn_cell_impl.py", line 180, in __call__
    return super(RNNCell, self).__call__(inputs, state)
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\layers\base.py", line 441, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\rnn_cell_impl.py", line 383, in call
    concat = _linear([inputs, h], 4 * self._num_units, True)
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\rnn_cell_impl.py", line 1021, in _linear
    res = math_ops.matmul(array_ops.concat(args, 1), weights)
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\math_ops.py", line 1816, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 1217, in _mat_mul
    transpose_b=transpose_b, name=name)
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

InternalError (see above for traceback): Blas GEMM launch failed : a.shape=(269, 14), b.shape=(14, 40), m=269, n=40, k=14
	 [[Node: rnn/while/rnn/basic_lstm_cell/basic_lstm_cell/MatMul = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/gpu:0"](rnn/while/rnn/basic_lstm_cell/basic_lstm_cell/concat, rnn/while/rnn/basic_lstm_cell/basic_lstm_cell/MatMul/Enter)]]
	 [[Node: Sum/_5 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_800_Sum", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]


In [ ]:
denormalizedTestPredictY=[item for sublist in test_predict for item in sublist]

In [ ]:
rootMeanSquaredError(denormalizedTestY,denormalizedTestPredictY)

In [ ]:
121 in denormalizedTestY

In [ ]:
test_predict