lstm2

과정 요약:<br> 
feature: season, day of week, week number, sales <br> 
feature engineering: 이상점 제거+ normalize+ denormalize

결과요약: RMSE: 0.24234837293624878 

상세과정:
주중(1)/주말(2) + 겨울(1)봄(2)여름(3)가을(4) // 
이미 lstm이라는 것이 sequence 개념이 있으므로 시간축(1~397)를 feature로 설정하는 것은 의미가 없을 듯 하여 LSTM 시도2에서는 제외함

추가의견) 개인적으로 이상점을 제거한 후 normalize를 하면 rmse가 커질 수 밖에 없다고 생각함. 다음시도(lstm3)은 이상점을 제거하지 않고 normalize를 하고, lstm4에서는 이상점을 제거하고 normalize를 하지 않는 것을 시도하겠다.

추가의견2) 처음에는 denormalize과정 없이 rmse를 구했는데, 이것보다는 denormalize를 한 후 rmse를 구하여 모델간 비교를 하는 것이 더 적절한 것 같다. normalize는 어디까지나 변환이니 항상 변환을 할때는 역변환을 하여 원본 데이터 형태m로 생각하는 것이 덜 헷갈리고, 결과값에 대한 더욱 직관적인 이해가 가능할 것 같다. 그리고, 여러 형태의 data transformation이 있는데 normalize 가장 마지막 단계의 data transformation인 것 같다. 다른 로그나 루트 변환을 한 후 normalization을 하고, 그리고 예측값이 모델을 통해 생성되면 바로 denormalize하고...예측(뉴럴) 모델의 input직전과 output직후.

In [1]:
import tensorflow as tf
import numpy as np
import matplotlib
import os
import matplotlib.pyplot as plt
import pandas as pd
from datetime import datetime   

set seednumber(7 or 77)

In [2]:
tf.set_random_seed(77)

# 1. DATA 준비

In [3]:
columns=['date','sales']

txs=pd.read_table('./lstmData/lstmPrac2.csv', sep=',',header=None,names=columns )
txs.info()
txs.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 397 entries, 0 to 396
Data columns (total 2 columns):
date     397 non-null object
sales    397 non-null int64
dtypes: int64(1), object(1)
memory usage: 6.3+ KB


date  sales
0  2016-01-01     34
1  2016-01-02     41
2  2016-01-03     54
3  2016-01-04     41
4  2016-01-05     35

## 1.1 기본 feature

'ds-y'의 ds로부터 api로 얻을 수 있는 값

year, day of week, month, week number를 기본 feature로 설정

In [4]:
year = lambda x: datetime.strptime(x, "%Y-%m-%d" ).year  
day_of_week = lambda x: datetime.strptime(x, "%Y-%m-%d" ).weekday()
month = lambda x: datetime.strptime(x, "%Y-%m-%d" ).month
# please read docs on how week numbers are calculate
week_number = lambda x: datetime.strptime(x, "%Y-%m-%d" ).strftime('%V')

In [5]:
txs['year'] = txs['date'].map(year)
txs['month']=txs['date'].map(month)
txs['week_number']=txs['date'].map(week_number)
txs['day_of_week']=txs['date'].map(day_of_week)

## 1.2 추가 feature

'ds-y'의 ds로부터 api로 얻을 수 없는 값: 본 feature를 가공한 feature + ds와 무관한 feature

In [6]:
seasons = [0,0,1,1,1,2,2,2,3,3,3,0] #dec - feb is winter, then spring, summer, fall etc
season = lambda x: seasons[(datetime.strptime(x, "%Y-%m-%d" ).month-1)]

In [7]:
txs['season']=txs['date'].map(season)
txs

date  sales  year  month week_number  day_of_week  season
0    2016-01-01     34  2016      1          53            4       0
1    2016-01-02     41  2016      1          53            5       0
2    2016-01-03     54  2016      1          53            6       0
3    2016-01-04     41  2016      1          01            0       0
4    2016-01-05     35  2016      1          01            1       0
5    2016-01-06     44  2016      1          01            2       0
6    2016-01-07     50  2016      1          01            3       0
7    2016-01-08     42  2016      1          01            4       0
8    2016-01-09     42  2016      1          01            5       0
9    2016-01-10     66  2016      1          01            6       0
10   2016-01-11     50  2016      1          02            0       0
11   2016-01-12     55  2016      1          02            1       0
12   2016-01-13     56  2016      1          02            2       0
13   2016-01-14     53  2016      1          02            3       0
14   2016-01-15     44  2016      1          02            4       0
15   2016-01-16     54  2016      1          02            5       0
16   2016-01-17     54  2016      1          02            6       0
17   2016-01-18     50  2016      1          03            0       0
18   2016-01-19     40  2016      1          03            1       0
19   2016-01-20     49  2016      1          03            2       0
20   2016-01-21     28  2016      1          03            3       0
21   2016-01-22     72  2016      1          03            4       0
22   2016-01-23     71  2016      1          03            5       0
23   2016-01-24     53  2016      1          03            6       0
24   2016-01-25     43  2016      1          04            0       0
25   2016-01-26     38  2016      1          04            1       0
26   2016-01-27     55  2016      1          04            2       0
27   2016-01-28     49  2016      1          04            3       0
28   2016-01-29     43  2016      1          04            4       0
29   2016-01-30     49  2016      1          04            5       0
..          ...    ...   ...    ...         ...          ...     ...
367  2017-01-02     16  2017      1          01            0       0
368  2017-01-03     20  2017      1          01            1       0
369  2017-01-04     12  2017      1          01            2       0
370  2017-01-05     11  2017      1          01            3       0
371  2017-01-06     22  2017      1          01            4       0
372  2017-01-07     20  2017      1          01            5       0
373  2017-01-08     16  2017      1          01            6       0
374  2017-01-09     17  2017      1          02            0       0
375  2017-01-10     97  2017      1          02            1       0
376  2017-01-11      0  2017      1          02            2       0
377  2017-01-12     23  2017      1          02            3       0
378  2017-01-13    100  2017      1          02            4       0
379  2017-01-14     18  2017      1          02            5       0
380  2017-01-15     13  2017      1          02            6       0
381  2017-01-16     21  2017      1          03            0       0
382  2017-01-17     24  2017      1          03            1       0
383  2017-01-18     16  2017      1          03            2       0
384  2017-01-19     18  2017      1          03            3       0
385  2017-01-20     22  2017      1          03            4       0
386  2017-01-21     18  2017      1          03            5       0
387  2017-01-22     11  2017      1          03            6       0
388  2017-01-23     24  2017      1          04            0       0
389  2017-01-24     22  2017      1          04            1       0
390  2017-01-25     20  2017      1          04            2       0
391  2017-01-26     22  2017      1          04            3       0
392  2017-01-27     26  2017      1          04            4       0
393  2017

pandas를 통해 구한 각 feature는 list()로 우리의 기준type인 list로 변경이 가능

## 1.3 추가 가공

### 1.3.1 y의 추가 가공

이상점 제거, normalization, bucketization 을 하여 새로운 열을 생성하는 방향으로

In [8]:
sales=list(txs['sales'])

#### 이상점 제거

이상점 제거를 위해 평균과 표준편차를 구한다. 이상점의 기준은 일단 평균+-2*sd로 설정

In [9]:
mean=np.mean(sales)
std=np.std(sales)

In [10]:
for i in range(len(sales)):
    if (sales[i]<mean-2*std or sales[i]>mean+2*std):
         sales[i]=int(mean)
        

In [11]:
sales

[34,
 41,
 54,
 41,
 35,
 44,
 50,
 42,
 42,
 66,
 50,
 55,
 56,
 53,
 44,
 54,
 54,
 50,
 40,
 49,
 28,
 72,
 71,
 53,
 43,
 38,
 55,
 49,
 43,
 49,
 49,
 44,
 39,
 52,
 45,
 33,
 43,
 40,
 46,
 49,
 50,
 37,
 37,
 45,
 48,
 48,
 38,
 60,
 31,
 35,
 53,
 70,
 62,
 48,
 51,
 49,
 38,
 32,
 39,
 35,
 30,
 36,
 31,
 31,
 44,
 41,
 41,
 45,
 46,
 45,
 41,
 47,
 48,
 40,
 42,
 38,
 38,
 45,
 48,
 62,
 46,
 38,
 62,
 81,
 40,
 45,
 42,
 53,
 53,
 56,
 53,
 47,
 61,
 64,
 62,
 37,
 65,
 54,
 44,
 46,
 50,
 43,
 53,
 63,
 52,
 2,
 0,
 0,
 72,
 59,
 75,
 47,
 44,
 77,
 90,
 93,
 47,
 61,
 77,
 35,
 50,
 58,
 33,
 41,
 36,
 64,
 49,
 53,
 60,
 43,
 41,
 55,
 45,
 18,
 60,
 69,
 54,
 39,
 50,
 44,
 54,
 57,
 82,
 57,
 44,
 56,
 51,
 55,
 28,
 56,
 54,
 36,
 12,
 25,
 41,
 11,
 6,
 9,
 35,
 29,
 24,
 23,
 14,
 21,
 20,
 25,
 23,
 27,
 31,
 16,
 14,
 30,
 32,
 75,
 35,
 26,
 12,
 21,
 23,
 28,
 25,
 31,
 21,
 17,
 10,
 29,
 34,
 28,
 20,
 36,
 23,
 15,
 42,
 28,
 24,
 29,
 20,
 14,
 18,
 27,
 22,


#### Normalization

In [12]:
def minMaxNormalizer(data):
    numerator=data-np.min(data)
    denominator=np.max(data)-np.min(data)
    return numerator/(denominator+1e-7)

In [13]:
originalSales=sales

In [14]:
sales=minMaxNormalizer(sales)

In [15]:
sales

array([ 0.34,  0.41,  0.54,  0.41,  0.35,  0.44,  0.5 ,  0.42,  0.42,
        0.66,  0.5 ,  0.55,  0.56,  0.53,  0.44,  0.54,  0.54,  0.5 ,
        0.4 ,  0.49,  0.28,  0.72,  0.71,  0.53,  0.43,  0.38,  0.55,
        0.49,  0.43,  0.49,  0.49,  0.44,  0.39,  0.52,  0.45,  0.33,
        0.43,  0.4 ,  0.46,  0.49,  0.5 ,  0.37,  0.37,  0.45,  0.48,
        0.48,  0.38,  0.6 ,  0.31,  0.35,  0.53,  0.7 ,  0.62,  0.48,
        0.51,  0.49,  0.38,  0.32,  0.39,  0.35,  0.3 ,  0.36,  0.31,
        0.31,  0.44,  0.41,  0.41,  0.45,  0.46,  0.45,  0.41,  0.47,
        0.48,  0.4 ,  0.42,  0.38,  0.38,  0.45,  0.48,  0.62,  0.46,
        0.38,  0.62,  0.81,  0.4 ,  0.45,  0.42,  0.53,  0.53,  0.56,
        0.53,  0.47,  0.61,  0.64,  0.62,  0.37,  0.65,  0.54,  0.44,
        0.46,  0.5 ,  0.43,  0.53,  0.63,  0.52,  0.02,  0.  ,  0.  ,
        0.72,  0.59,  0.75,  0.47,  0.44,  0.77,  0.9 ,  0.93,  0.47,
        0.61,  0.77,  0.35,  0.5 ,  0.58,  0.33,  0.41,  0.36,  0.64,
        0.49,  0.53,

#### Denormalization

예측모델을 통해 얻은 sales결과를 denormalize시켜 기존 단위로 변환

In [16]:
def minMaxDeNormalizer(data):
    shift=np.min(originalData)
    multiplier=np.max(originalData)-np.min(originalData)
    return (data+shift)*multiplier 

이 함수를 마지막 rmse구하기 전에 호출

## 1.4 합쳐서 최종 data 생성: XY

In [17]:
tempxy=[list(txs['season']),list(txs['day_of_week']),list(txs['week_number']),sales]

In [18]:
XY=np.array(tempxy).transpose().astype(np.float)

In [19]:
XY

array([[  0.00000000e+00,   4.00000000e+00,   5.30000000e+01,
          3.40000000e-01],
       [  0.00000000e+00,   5.00000000e+00,   5.30000000e+01,
          4.10000000e-01],
       [  0.00000000e+00,   6.00000000e+00,   5.30000000e+01,
          5.39999999e-01],
       ..., 
       [  0.00000000e+00,   6.00000000e+00,   4.00000000e+00,
          0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   5.00000000e+00,
          5.00000000e-02],
       [  0.00000000e+00,   1.00000000e+00,   5.00000000e+00,
          3.10000000e-01]])

# 2. MODEL 설계

## 2.1 사용 model 설정: RNN LSTM

## 2.2 해당 model의 train parameters 설정

In [20]:
#data_dim은 y값 도출을 위한 feature 가지수(독립변수 가지수 +1(y포함))
data_dim=4

#data_dim크기의 data 한 묶음이 seq_length만큼 input으로 들어가
seq_length=7

#output_dim(=forecastDays)만큼의 다음날 y_data를 예측
output_dim=1
forecastDays=1
#hidden_dim은 정말 임의로 설정
hidden_dim=10

#learning rate은 배우는 속도(너무 크지도, 작지도 않게 설정)
learning_rate=0.01

#iterations는 반복 횟수
iterations=1000

## 2.3 사용 model, train parameter에 맞추어 dataset(XY) 변환: dataX, dataY

In [22]:
X=XY
Y=XY[:,[-1]]

#build a series dataset(seq_length에 해당하는 전날 X와 다음 forecastDays에 해당하는 Y)
dataX=[]
dataY=[]
for i in range(0, len(Y)-seq_length):
    _x=X[i:i+seq_length]
    _y=Y[i+seq_length:i+seq_length+forecastDays]
    print(_x,"->",_y)
    dataX.append(_x)
    dataY.append(_y)

[[  0.     4.    53.     0.34]
 [  0.     5.    53.     0.41]
 [  0.     6.    53.     0.54]
 [  0.     0.     1.     0.41]
 [  0.     1.     1.     0.35]
 [  0.     2.     1.     0.44]
 [  0.     3.     1.     0.5 ]] -> [ 0.42]
[[  0.     5.    53.     0.41]
 [  0.     6.    53.     0.54]
 [  0.     0.     1.     0.41]
 [  0.     1.     1.     0.35]
 [  0.     2.     1.     0.44]
 [  0.     3.     1.     0.5 ]
 [  0.     4.     1.     0.42]] -> [ 0.42]
[[  0.     6.    53.     0.54]
 [  0.     0.     1.     0.41]
 [  0.     1.     1.     0.35]
 [  0.     2.     1.     0.44]
 [  0.     3.     1.     0.5 ]
 [  0.     4.     1.     0.42]
 [  0.     5.     1.     0.42]] -> [ 0.66]
[[ 0.    0.    1.    0.41]
 [ 0.    1.    1.    0.35]
 [ 0.    2.    1.    0.44]
 [ 0.    3.    1.    0.5 ]
 [ 0.    4.    1.    0.42]
 [ 0.    5.    1.    0.42]
 [ 0.    6.    1.    0.66]] -> [ 0.5]
[[ 0.    1.    1.    0.35]
 [ 0.    2.    1.    0.44]
 [ 0.    3.    1.    0.5 ]
 [ 0.    4.    1.    0.42]
 [ 0.

[[  1.     0.    18.     0.33]
 [  1.     1.    18.     0.41]
 [  1.     2.    18.     0.36]
 [  1.     3.    18.     0.64]
 [  1.     4.    18.     0.49]
 [  1.     5.    18.     0.53]
 [  1.     6.    18.     0.6 ]] -> [ 0.43]
[[  1.     1.    18.     0.41]
 [  1.     2.    18.     0.36]
 [  1.     3.    18.     0.64]
 [  1.     4.    18.     0.49]
 [  1.     5.    18.     0.53]
 [  1.     6.    18.     0.6 ]
 [  1.     0.    19.     0.43]] -> [ 0.41]
[[  1.     2.    18.     0.36]
 [  1.     3.    18.     0.64]
 [  1.     4.    18.     0.49]
 [  1.     5.    18.     0.53]
 [  1.     6.    18.     0.6 ]
 [  1.     0.    19.     0.43]
 [  1.     1.    19.     0.41]] -> [ 0.55]
[[  1.     3.    18.     0.64]
 [  1.     4.    18.     0.49]
 [  1.     5.    18.     0.53]
 [  1.     6.    18.     0.6 ]
 [  1.     0.    19.     0.43]
 [  1.     1.    19.     0.41]
 [  1.     2.    19.     0.55]] -> [ 0.45]
[[  1.     4.    18.     0.49]
 [  1.     5.    18.     0.53]
 [  1.     6.    18.  

## 2.4 train/test split

In [ ]:
train_size = int(len(dataY) * 0.7)
test_size = len(dataY) - train_size
trainX, testX = np.array(dataX[0:train_size]), np.array(dataX[train_size:])
trainY, testY = np.array(dataY[0:train_size]), np.array(dataY[train_size:])

## 2.5 input place holders

X의 경우 input type과 [batch size, sequence length, input data dimension(feature+1))]

Y의 경우 input type과 [batch size, 원하는 output 의 개수(forecast days)]

In [ ]:
X=tf.placeholder(tf.float32, [None, seq_length, data_dim])
Y=tf.placeholder(tf.float32, [None, forecastDays])

In [ ]:
# build a LSTM network(input: cell shape, type/ )
cell = tf.contrib.rnn.BasicLSTMCell(num_units=hidden_dim, state_is_tuple=True, activation=None)
outputs, _states = tf.nn.dynamic_rnn(cell, X, dtype=tf.float32)

# use the last cell's output to calculate Y_pred
Y_pred = tf.contrib.layers.fully_connected(outputs[:, -1], output_dim, activation_fn=tf.tanh) 
# cost/loss
loss = tf.reduce_sum(tf.square(Y_pred - Y))  # sum of the squares
# optimizer
optimizer = tf.train.AdamOptimizer(learning_rate)
train = optimizer.minimize(loss)
# RMSE
targets = tf.placeholder(tf.float32, [None, 1])
predictions = tf.placeholder(tf.float32, [None, 1])
rmse = tf.sqrt(tf.reduce_mean(tf.square(targets - predictions)))

## 2.5 Train and Test

In [24]:
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)

    # Training step
    for i in range(iterations):
        _, step_loss = sess.run([train, loss], feed_dict={X: trainX, Y: trainY})
        print("[step: {}] loss: {}".format(i, step_loss))

    # Test step
    test_predict = sess.run(Y_pred, feed_dict={X: testX})
    rmse_val = sess.run(rmse, feed_dict={targets: testY, predictions: test_predict})
    print("RMSE: {}".format(rmse_val))

    # Plot predictions
    plt.plot(testY)
    plt.plot(test_predict)
    plt.xlabel("Time Period")
    plt.ylabel("Stock Price")
    plt.show()

NameError: name 'train' is not defined