lstm6

결과요약: RMSE: 0.15565380454063416  sales를 log를 취한 후 normalize한다.

seed 7: [step: 499] loss: 1.981953740119934
RMSE: 0.15565380454063416

seed 77: [step: 499] loss: 2.095550537109375
RMSE: 0.1802239865064621

시도 내용 요약:
주중(1)/주말(2) + 겨울(1)봄(2)여름(3)가을(4) // 

이미 lstm이라는 것이 sequence 개념이 있으므로 시간축(1~397)를 feature로 설정하는 것은 의미가 없을 듯 하여 제외함

In [1]:
import tensorflow as tf
import numpy as np
import matplotlib
import os
import matplotlib.pyplot as plt
import pandas as pd
tf.set_random_seed(77)


In [2]:
columns=['date','sales']

txs=pd.read_table('./lstmData/lstmPrac3.csv', sep=',',header=None,names=columns )
txs.info()
txs.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 397 entries, 0 to 396
Data columns (total 2 columns):
date     397 non-null object
sales    397 non-null int64
dtypes: int64(1), object(1)
memory usage: 6.3+ KB


date  sales
0  2016-01-01     34
1  2016-01-02     41
2  2016-01-03     54
3  2016-01-04     41
4  2016-01-05     35

In [3]:
from datetime import datetime                    

# 1. 기본 feature

In [4]:
year = lambda x: datetime.strptime(x, "%Y-%m-%d" ).year  
day_of_week = lambda x: datetime.strptime(x, "%Y-%m-%d" ).weekday()
month = lambda x: datetime.strptime(x, "%Y-%m-%d" ).month
# please read docs on how week numbers are calculate
week_number = lambda x: datetime.strptime(x, "%Y-%m-%d" ).strftime('%V')

# 2. 추가 feature

In [5]:
seasons = [0,0,1,1,1,2,2,2,3,3,3,0] #dec - feb is winter, then spring, summer, fall etc
season = lambda x: seasons[(datetime.strptime(x, "%Y-%m-%d" ).month-1)]

In [6]:
txs['year'] = txs['date'].map(year)
txs['month']=txs['date'].map(month)
txs['week_number']=txs['date'].map(week_number)
txs['season']=txs['date'].map(season)
txs['day_of_week']=txs['date'].map(day_of_week)
txs

date  sales  year  month week_number  season  day_of_week
0    2016-01-01     34  2016      1          53       0            4
1    2016-01-02     41  2016      1          53       0            5
2    2016-01-03     54  2016      1          53       0            6
3    2016-01-04     41  2016      1          01       0            0
4    2016-01-05     35  2016      1          01       0            1
5    2016-01-06     44  2016      1          01       0            2
6    2016-01-07     50  2016      1          01       0            3
7    2016-01-08     42  2016      1          01       0            4
8    2016-01-09     42  2016      1          01       0            5
9    2016-01-10     66  2016      1          01       0            6
10   2016-01-11     50  2016      1          02       0            0
11   2016-01-12     55  2016      1          02       0            1
12   2016-01-13     56  2016      1          02       0            2
13   2016-01-14     53  2016      1          02       0            3
14   2016-01-15     44  2016      1          02       0            4
15   2016-01-16     54  2016      1          02       0            5
16   2016-01-17     54  2016      1          02       0            6
17   2016-01-18     50  2016      1          03       0            0
18   2016-01-19     40  2016      1          03       0            1
19   2016-01-20     49  2016      1          03       0            2
20   2016-01-21     28  2016      1          03       0            3
21   2016-01-22     72  2016      1          03       0            4
22   2016-01-23     71  2016      1          03       0            5
23   2016-01-24     53  2016      1          03       0            6
24   2016-01-25     43  2016      1          04       0            0
25   2016-01-26     38  2016      1          04       0            1
26   2016-01-27     55  2016      1          04       0            2
27   2016-01-28     49  2016      1          04       0            3
28   2016-01-29     43  2016      1          04       0            4
29   2016-01-30     49  2016      1          04       0            5
..          ...    ...   ...    ...         ...     ...          ...
367  2017-01-02     16  2017      1          01       0            0
368  2017-01-03     20  2017      1          01       0            1
369  2017-01-04     12  2017      1          01       0            2
370  2017-01-05     11  2017      1          01       0            3
371  2017-01-06     22  2017      1          01       0            4
372  2017-01-07     20  2017      1          01       0            5
373  2017-01-08     16  2017      1          01       0            6
374  2017-01-09     17  2017      1          02       0            0
375  2017-01-10     97  2017      1          02       0            1
376  2017-01-11      1  2017      1          02       0            2
377  2017-01-12     23  2017      1          02       0            3
378  2017-01-13    100  2017      1          02       0            4
379  2017-01-14     18  2017      1          02       0            5
380  2017-01-15     13  2017      1          02       0            6
381  2017-01-16     21  2017      1          03       0            0
382  2017-01-17     24  2017      1          03       0            1
383  2017-01-18     16  2017      1          03       0            2
384  2017-01-19     18  2017      1          03       0            3
385  2017-01-20     22  2017      1          03       0            4
386  2017-01-21     18  2017      1          03       0            5
387  2017-01-22     11  2017      1          03       0            6
388  2017-01-23     24  2017      1          04       0            0
389  2017-01-24     22  2017      1          04       0            1
390  2017-01-25     20  2017      1          04       0            2
391  2017-01-26     22  2017      1          04       0            3
392  2017-01-27     26  2017      1          04       0            4
393  2017

pandas를 통해 구한 각 feature는 list()로 우리의 기준type인 list로 변경이 가능

# 3. 추가 가공

## 3.1 y의 추가 가공

In [7]:
xySales=txs['sales']
xySales=list(xySales)

### 이상점 제거

이상점 제거의 기준이 무척 주관적일 수 있으므로 제외하는 것이 좋을 수도 있어 lstm6는 이상점 제거를 하지 않았다.

normalization, bucketization 을 하여 새로운 열을 생성하는 방향으로

### log

In [8]:
xySales=np.log(xySales)
xySales

array([ 3.52636052,  3.71357207,  3.98898405,  3.71357207,  3.55534806,
        3.78418963,  3.91202301,  3.73766962,  3.73766962,  4.18965474,
        3.91202301,  4.00733319,  4.02535169,  3.97029191,  3.78418963,
        3.98898405,  3.98898405,  3.91202301,  3.68887945,  3.8918203 ,
        3.33220451,  4.27666612,  4.26267988,  3.97029191,  3.76120012,
        3.63758616,  4.00733319,  3.8918203 ,  3.76120012,  3.8918203 ,
        3.8918203 ,  3.78418963,  3.66356165,  3.95124372,  3.80666249,
        3.49650756,  3.76120012,  3.68887945,  3.8286414 ,  3.8918203 ,
        3.91202301,  3.61091791,  3.61091791,  3.80666249,  3.87120101,
        3.87120101,  3.63758616,  4.09434456,  3.4339872 ,  3.55534806,
        3.97029191,  4.24849524,  4.12713439,  3.87120101,  3.93182563,
        3.8918203 ,  3.63758616,  3.4657359 ,  3.66356165,  3.55534806,
        3.40119738,  3.58351894,  3.4339872 ,  3.4339872 ,  3.78418963,
        3.71357207,  3.71357207,  3.80666249,  3.8286414 ,  3.80

### Normalization

In [9]:
def MinMaxScaler(data):
    numerator=data-np.min(data)
    denominator=np.max(data)-np.min(data)
    return numerator/(denominator+1e-7)

In [10]:
xySales=MinMaxScaler(xySales)

## 합쳐서 최종 input XY생성

In [11]:
tempxy=[list(txs['season']),list(txs['day_of_week']),list(txs['week_number']),xySales]

In [12]:
tempxy

[[0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,


In [13]:
xy=np.array(tempxy)

In [14]:
xy

array([['0', '0', '0', ..., '0', '0', '0'],
       ['4', '5', '6', ..., '6', '0', '1'],
       ['53', '53', '53', ..., '04', '05', '05'],
       ['0.5557142370799633', '0.5852166429054146', '0.6286184327116974',
        ..., '0.0', '0.2536290760381732', '0.5411572543878042']], 
      dtype='<U32')

In [15]:
temp=xy.transpose()

In [16]:
temp

array([['0', '4', '53', '0.5557142370799633'],
       ['0', '5', '53', '0.5852166429054146'],
       ['0', '6', '53', '0.6286184327116974'],
       ..., 
       ['0', '6', '04', '0.0'],
       ['0', '0', '05', '0.2536290760381732'],
       ['0', '1', '05', '0.5411572543878042']], 
      dtype='<U32')

In [17]:
xy = temp.astype(np.float)

In [18]:
xy

array([[  0.        ,   4.        ,  53.        ,   0.55571424],
       [  0.        ,   5.        ,  53.        ,   0.58521664],
       [  0.        ,   6.        ,  53.        ,   0.62861843],
       ..., 
       [  0.        ,   6.        ,   4.        ,   0.        ],
       [  0.        ,   0.        ,   5.        ,   0.25362908],
       [  0.        ,   1.        ,   5.        ,   0.54115725]])

In [19]:
#train parameters
seq_length=7
data_dim=4
hidden_dim=10
output_dim=1
learning_rate=0.01
iterations=500
#기본형식
#기본 인자로는 ds-y로 받고 
#처리함수에서 ds를 받아서 'feature 처리모듈'에서 ds에서 요일(주중, 주말), 월(계절) + 날씨와 같은 추가 요인-값을 받는다.


x=xy
y=xy[:,[-1]]

#build a dataset
dataX=[]
dataY=[]
for i in range(0, len(y)-seq_length):
    _x=x[i:i+seq_length]
    _y=y[i+seq_length]
    print(_x,"->",_y)
    dataX.append(_x)
    dataY.append(_y)

# train/test split
train_size = int(len(dataY) * 0.7)
test_size = len(dataY) - train_size
trainX, testX = np.array(dataX[0:train_size]), np.array(dataX[train_size:])
trainY, testY = np.array(dataY[0:train_size]), np.array(dataY[train_size:])

#input place holders
X=tf.placeholder(tf.float32, [None, seq_length, data_dim])
Y=tf.placeholder(tf.float32, [None, 1])
# build a LSTM network(input: cell shape, type/ )
cell = tf.contrib.rnn.BasicLSTMCell(num_units=hidden_dim, state_is_tuple=True, activation=tf.tanh)
outputs, _states = tf.nn.dynamic_rnn(cell, X, dtype=tf.float32)

# use the last cell's output to calculate Y_pred
Y_pred = tf.contrib.layers.fully_connected(outputs[:, -1], output_dim, activation_fn=tf.tanh) 
# cost/loss
loss = tf.reduce_sum(tf.square(Y_pred - Y))  # sum of the squares
# optimizer
optimizer = tf.train.AdamOptimizer(learning_rate)
train = optimizer.minimize(loss)
# RMSE
targets = tf.placeholder(tf.float32, [None, 1])
predictions = tf.placeholder(tf.float32, [None, 1])
rmse = tf.sqrt(tf.reduce_mean(tf.square(targets - predictions)))
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)

    # Training step
    for i in range(iterations):
        _, step_loss = sess.run([train, loss], feed_dict={
                                X: trainX, Y: trainY})
        print("[step: {}] loss: {}".format(i, step_loss))

    # Test step
    test_predict = sess.run(Y_pred, feed_dict={X: testX})
    rmse_val = sess.run(rmse, feed_dict={
                    targets: testY, predictions: test_predict})
    print("RMSE: {}".format(rmse_val))

    # Plot predictions
    plt.plot(testY)
    plt.plot(test_predict)
    plt.xlabel("Time Period")
    plt.ylabel("Stock Price")
    plt.show()

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)

    # Training step
    for i in range(iterations):
        _, step_loss = sess.run([train, loss], feed_dict={
                                X: trainX, Y: trainY})
        print("[step: {}] loss: {}".format(i, step_loss))

    # Test step
    test_predict = sess.run(Y_pred, feed_dict={X: testX})
    rmse_val = sess.run(rmse, feed_dict={
                    targets: testY, predictions: test_predict})
    print("RMSE: {}".format(rmse_val))

    # Plot predictions
    plt.plot(testY)
    plt.plot(test_predict)
    plt.xlabel("Time Period")
    plt.ylabel("Stock Price")
    plt.show()


[[  0.           4.          53.           0.55571424]
 [  0.           5.          53.           0.58521664]
 [  0.           6.          53.           0.62861843]
 [  0.           0.           1.           0.58521664]
 [  0.           1.           1.           0.56028234]
 [  0.           2.           1.           0.59634517]
 [  0.           3.           1.           0.61649025]] -> [ 0.58901414]
[[  0.           5.          53.           0.58521664]
 [  0.           6.          53.           0.62861843]
 [  0.           0.           1.           0.58521664]
 [  0.           1.           1.           0.56028234]
 [  0.           2.           1.           0.59634517]
 [  0.           3.           1.           0.61649025]
 [  0.           4.           1.           0.58901414]] -> [ 0.58901414]
[[  0.           6.          53.           0.62861843]
 [  0.           0.           1.           0.58521664]
 [  0.           1.           1.           0.56028234]
 [  0.           2.          

 [  1.           6.          17.           0.63987955]] -> [ 0.55100975]
[[  1.           1.          17.           0.60673939]
 [  1.           2.          17.           0.64782688]
 [  1.           3.          17.           0.68453424]
 [  1.           4.          17.           0.88910027]
 [  1.           5.          17.           0.61649025]
 [  1.           6.          17.           0.63987955]
 [  1.           0.          18.           0.55100975]] -> [ 0.58521664]
[[  1.           2.          17.           0.64782688]
 [  1.           3.          17.           0.68453424]
 [  1.           4.          17.           0.88910027]
 [  1.           5.          17.           0.61649025]
 [  1.           6.          17.           0.63987955]
 [  1.           0.          18.           0.55100975]
 [  1.           1.          18.           0.58521664]] -> [ 0.56472175]
[[  1.           3.          17.           0.68453424]
 [  1.           4.          17.           0.88910027]
 [  1.     

InternalError: Blas GEMM launch failed : a.shape=(273, 14), b.shape=(14, 40), m=273, n=40, k=14
	 [[Node: rnn/while/rnn/basic_lstm_cell/basic_lstm_cell/MatMul = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/gpu:0"](rnn/while/rnn/basic_lstm_cell/basic_lstm_cell/concat, rnn/while/rnn/basic_lstm_cell/basic_lstm_cell/MatMul/Enter)]]
	 [[Node: Sum/_5 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_803_Sum", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op 'rnn/while/rnn/basic_lstm_cell/basic_lstm_cell/MatMul', defined at:
  File "c:\users\user\anaconda3\envs\tensorflow\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\user\anaconda3\envs\tensorflow\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\ipykernel\kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\zmq\eventloop\ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\tornado\ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\zmq\eventloop\zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\zmq\eventloop\zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\zmq\eventloop\zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\ipykernel\kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\ipykernel\ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\ipykernel\zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\IPython\core\interactiveshell.py", line 2698, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\IPython\core\interactiveshell.py", line 2802, in run_ast_nodes
    if self.run_code(code, result):
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\IPython\core\interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-19-ee267a0c1a75>", line 37, in <module>
    outputs, _states = tf.nn.dynamic_rnn(cell, X, dtype=tf.float32)
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\rnn.py", line 574, in dynamic_rnn
    dtype=dtype)
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\rnn.py", line 737, in _dynamic_rnn_loop
    swap_memory=swap_memory)
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2770, in while_loop
    result = context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2599, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2549, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\rnn.py", line 722, in _time_step
    (output, new_state) = call_cell()
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\rnn.py", line 708, in <lambda>
    call_cell = lambda: cell(input_t, state)
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\rnn_cell_impl.py", line 180, in __call__
    return super(RNNCell, self).__call__(inputs, state)
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\layers\base.py", line 441, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\rnn_cell_impl.py", line 383, in call
    concat = _linear([inputs, h], 4 * self._num_units, True)
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\rnn_cell_impl.py", line 1021, in _linear
    res = math_ops.matmul(array_ops.concat(args, 1), weights)
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\math_ops.py", line 1816, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 1217, in _mat_mul
    transpose_b=transpose_b, name=name)
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "c:\users\user\anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

InternalError (see above for traceback): Blas GEMM launch failed : a.shape=(273, 14), b.shape=(14, 40), m=273, n=40, k=14
	 [[Node: rnn/while/rnn/basic_lstm_cell/basic_lstm_cell/MatMul = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/gpu:0"](rnn/while/rnn/basic_lstm_cell/basic_lstm_cell/concat, rnn/while/rnn/basic_lstm_cell/basic_lstm_cell/MatMul/Enter)]]
	 [[Node: Sum/_5 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_803_Sum", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
