lstm3

과정 요약:<br> 
feature: season, day of week, week number, sales <br> 
feature engineering: outlier delete + normalize + denormalize

결과요약: RMSE: 0.24234837293624878 

상세과정:
주중(1)/주말(2) + 겨울(1)봄(2)여름(3)가을(4) // 
이미 lstm이라는 것이 sequence 개념이 있으므로 시간축(1~397)를 feature로 설정하는 것은 의미가 없을 듯 하여 LSTM 시도2에서는 제외함

추가의견) 개인적으로 이상점을 제거한 후 normalize를 하면 rmse가 커질 수 밖에 없다고 생각함. 다음시도(lstm3)은 이상점을 제거하지 않고 normalize를 하고, lstm4에서는 이상점을 제거하고 normalize를 하지 않는 것을 시도하겠다.

추가의견2) 처음에는 denormalize과정 없이 rmse를 구했는데, 이것보다는 denormalize를 한 후 rmse를 구하여 모델간 비교를 하는 것이 더 적절한 것 같다. normalize는 어디까지나 변환이니 항상 변환을 할때는 역변환을 하여 원본 데이터 형태m로 생각하는 것이 덜 헷갈리고, 결과값에 대한 더욱 직관적인 이해가 가능할 것 같다. 그리고, 여러 형태의 data transformation이 있는데 normalize 가장 마지막 단계의 data transformation인 것 같다. 다른 로그나 루트 변환을 한 후 normalization을 하고, 그리고 예측값이 모델을 통해 생성되면 바로 denormalize하고...예측(뉴럴) 모델의 input직전과 output직후.

In [1]:
import tensorflow as tf
import numpy as np
import matplotlib
import os
import matplotlib.pyplot as plt
import pandas as pd
from datetime import datetime   

set seednumber(7 or 77)

In [2]:
tf.set_random_seed(7)

# 1. DATA 준비

In [3]:
columns=['date','sales']

txs=pd.read_table('./lstmData/lstmPrac2.csv', sep=',',header=None,names=columns )
txs.info()
txs.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 397 entries, 0 to 396
Data columns (total 2 columns):
date     397 non-null object
sales    397 non-null int64
dtypes: int64(1), object(1)
memory usage: 6.3+ KB


date  sales
0  2016-01-01     34
1  2016-01-02     41
2  2016-01-03     54
3  2016-01-04     41
4  2016-01-05     35

In [4]:
sales=list(txs['sales'])

## 1.1 기본 feature

'ds-y'의 ds로부터 api로 얻을 수 있는 값

year, day of week, month, week number를 기본 feature로 설정

In [5]:
year = lambda x: datetime.strptime(x, "%Y-%m-%d" ).year  
day_of_week = lambda x: datetime.strptime(x, "%Y-%m-%d" ).weekday()
month = lambda x: datetime.strptime(x, "%Y-%m-%d" ).month
# please read docs on how week numbers are calculate
week_number = lambda x: datetime.strptime(x, "%Y-%m-%d" ).strftime('%V')

In [6]:
txs['year'] = txs['date'].map(year)
txs['month']=txs['date'].map(month)
txs['week_number']=txs['date'].map(week_number)
txs['day_of_week']=txs['date'].map(day_of_week)

## 1.2 추가 feature

'ds-y'의 ds로부터 api로 얻을 수 없는 값: 본 feature를 가공한 feature + ds와 무관한 feature

In [7]:
seasons = [0,0,1,1,1,2,2,2,3,3,3,0] #dec - feb is winter, then spring, summer, fall etc
season = lambda x: seasons[(datetime.strptime(x, "%Y-%m-%d" ).month-1)]

In [8]:
txs['season']=txs['date'].map(season)
txs

date  sales  year  month week_number  day_of_week  season
0    2016-01-01     34  2016      1          53            4       0
1    2016-01-02     41  2016      1          53            5       0
2    2016-01-03     54  2016      1          53            6       0
3    2016-01-04     41  2016      1          01            0       0
4    2016-01-05     35  2016      1          01            1       0
5    2016-01-06     44  2016      1          01            2       0
6    2016-01-07     50  2016      1          01            3       0
7    2016-01-08     42  2016      1          01            4       0
8    2016-01-09     42  2016      1          01            5       0
9    2016-01-10     66  2016      1          01            6       0
10   2016-01-11     50  2016      1          02            0       0
11   2016-01-12     55  2016      1          02            1       0
12   2016-01-13     56  2016      1          02            2       0
13   2016-01-14     53  2016      1          02            3       0
14   2016-01-15     44  2016      1          02            4       0
15   2016-01-16     54  2016      1          02            5       0
16   2016-01-17     54  2016      1          02            6       0
17   2016-01-18     50  2016      1          03            0       0
18   2016-01-19     40  2016      1          03            1       0
19   2016-01-20     49  2016      1          03            2       0
20   2016-01-21     28  2016      1          03            3       0
21   2016-01-22     72  2016      1          03            4       0
22   2016-01-23     71  2016      1          03            5       0
23   2016-01-24     53  2016      1          03            6       0
24   2016-01-25     43  2016      1          04            0       0
25   2016-01-26     38  2016      1          04            1       0
26   2016-01-27     55  2016      1          04            2       0
27   2016-01-28     49  2016      1          04            3       0
28   2016-01-29     43  2016      1          04            4       0
29   2016-01-30     49  2016      1          04            5       0
..          ...    ...   ...    ...         ...          ...     ...
367  2017-01-02     16  2017      1          01            0       0
368  2017-01-03     20  2017      1          01            1       0
369  2017-01-04     12  2017      1          01            2       0
370  2017-01-05     11  2017      1          01            3       0
371  2017-01-06     22  2017      1          01            4       0
372  2017-01-07     20  2017      1          01            5       0
373  2017-01-08     16  2017      1          01            6       0
374  2017-01-09     17  2017      1          02            0       0
375  2017-01-10     97  2017      1          02            1       0
376  2017-01-11      0  2017      1          02            2       0
377  2017-01-12     23  2017      1          02            3       0
378  2017-01-13    100  2017      1          02            4       0
379  2017-01-14     18  2017      1          02            5       0
380  2017-01-15     13  2017      1          02            6       0
381  2017-01-16     21  2017      1          03            0       0
382  2017-01-17     24  2017      1          03            1       0
383  2017-01-18     16  2017      1          03            2       0
384  2017-01-19     18  2017      1          03            3       0
385  2017-01-20     22  2017      1          03            4       0
386  2017-01-21     18  2017      1          03            5       0
387  2017-01-22     11  2017      1          03            6       0
388  2017-01-23     24  2017      1          04            0       0
389  2017-01-24     22  2017      1          04            1       0
390  2017-01-25     20  2017      1          04            2       0
391  2017-01-26     22  2017      1          04            3       0
392  2017-01-27     26  2017      1          04            4       0
393  2017

pandas를 통해 구한 각 feature는 list()로 우리의 기준type인 list로 변경이 가능

## 1.3 합친 후 normalize하여 최종 data 생성: XY

In [9]:
tempxy=[list(txs['season']),list(txs['day_of_week']),list(txs['week_number']),sales]

In [10]:
XY=np.array(tempxy).transpose().astype(np.float)

In [11]:
XY

array([[  0.,   4.,  53.,  34.],
       [  0.,   5.,  53.,  41.],
       [  0.,   6.,  53.,  54.],
       ..., 
       [  0.,   6.,   4.,   0.],
       [  0.,   0.,   5.,   5.],
       [  0.,   1.,   5.,  31.]])

## 1.3 추가 가공

### 1.3.1 y의 추가 가공

마지막rmse를 계산할 때 원본 데이터를 복원하기 위해 저장해놓음

In [12]:
originalSales=sales

이상점 제거, bucketization 을 하여 새로운 열을 생성하는 방향으로

#### 이상점 제거

이상점 제거를 위해 평균과 표준편차를 구한다. 이상점의 기준은 일단 평균+-2*sd로 설정

lstm2에서는 이상점 제거하지 않는다

### 1.3.2 x의 추가 가공

## 1.4 합친 후 normalize하여 최종 data 생성: XY

In [13]:
tempxy=[list(txs['season']),list(txs['day_of_week']),list(txs['week_number']),sales]

In [14]:
xy=np.array(tempxy).transpose().astype(np.float)

In [15]:
xy

array([[  0.,   4.,  53.,  34.],
       [  0.,   5.,  53.,  41.],
       [  0.,   6.,  53.,  54.],
       ..., 
       [  0.,   6.,   4.,   0.],
       [  0.,   0.,   5.,   5.],
       [  0.,   1.,   5.,  31.]])

#### Normalization

In [16]:
def minMaxNormalizer(data):
    numerator=data-np.min(data)
    denominator=np.max(data)-np.min(data)
    return numerator/(denominator+1e-7)

마지막rmse를 계산할 때 원본 데이터를 복원하기 위해 저장해놓음

In [17]:
originalSales=sales

Normalization이 필요한 열을 normalize시킴(현재는 sales에 해당하는 마지막 열만 normalize)

In [18]:
xy[:,-1]=minMaxNormalizer(xy[:,-1])

다른 열 ex) XY[:,-3]=minMaxNormalizer(XY[:,-3])

In [19]:
xy

array([[  0.00000000e+00,   4.00000000e+00,   5.30000000e+01,
          5.96491228e-02],
       [  0.00000000e+00,   5.00000000e+00,   5.30000000e+01,
          7.19298245e-02],
       [  0.00000000e+00,   6.00000000e+00,   5.30000000e+01,
          9.47368421e-02],
       ..., 
       [  0.00000000e+00,   6.00000000e+00,   4.00000000e+00,
          0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   5.00000000e+00,
          8.77192982e-03],
       [  0.00000000e+00,   1.00000000e+00,   5.00000000e+00,
          5.43859649e-02]])

In [20]:
xy[:,-1]

array([ 0.05964912,  0.07192982,  0.09473684,  0.07192982,  0.06140351,
        0.07719298,  0.0877193 ,  0.07368421,  0.07368421,  0.11578947,
        0.0877193 ,  0.09649123,  0.09824561,  0.09298246,  0.07719298,
        0.09473684,  0.09473684,  0.0877193 ,  0.07017544,  0.08596491,
        0.04912281,  0.12631579,  0.1245614 ,  0.09298246,  0.0754386 ,
        0.06666667,  0.09649123,  0.08596491,  0.0754386 ,  0.08596491,
        0.08596491,  0.07719298,  0.06842105,  0.09122807,  0.07894737,
        0.05789474,  0.0754386 ,  0.07017544,  0.08070175,  0.08596491,
        0.0877193 ,  0.06491228,  0.06491228,  0.07894737,  0.08421053,
        0.08421053,  0.06666667,  0.10526316,  0.05438596,  0.06140351,
        0.09298246,  0.12280702,  0.10877193,  0.08421053,  0.08947368,
        0.08596491,  0.06666667,  0.05614035,  0.06842105,  0.06140351,
        0.05263158,  0.06315789,  0.05438596,  0.05438596,  0.07719298,
        0.07192982,  0.07192982,  0.07894737,  0.08070175,  0.07

#### Denormalization

예측모델을 통해 얻은 sales결과를 denormalize시켜 기존 단위로 변환

In [21]:
def minMaxDeNormalizer(data, originalData):
    shift=np.min(originalData)
    multiplier=np.max(originalData)-np.min(originalData)
    return (data+shift)*multiplier 

이 함수를 마지막 rmse구하기 전에 호출

# 2. MODEL 설계

## 2.1 사용 model 정의: RNN LSTM

## 2.2 해당 model의 train parameters 설정

In [22]:
#data_dim은 y값 도출을 위한 feature 가지수(독립변수 가지수 +1(y포함))
data_dim=4

#data_dim크기의 data 한 묶음이 seq_length만큼 input으로 들어가
seq_length=7

#output_dim(=forecastDays)만큼의 다음날 y_data를 예측
forecastDays=1
output_dim=forecastDays

#hidden_dim은 정말 임의로 설정
hidden_dim=10

#learning rate은 배우는 속도(너무 크지도, 작지도 않게 설정)
learning_rate=0.01

#iterations는 반복 횟수
iterations=1000

## 2.3 사용 model, train parameter에 맞추어 dataset(XY) 변환: dataX, dataY

In [23]:
x=xy
y=xy[:,[-1]]

#build a series dataset(seq_length에 해당하는 전날 X와 다음 forecastDays에 해당하는 Y)
dataX=[]
dataY=[]
for i in range(0, len(y)-seq_length):
    _x=x[i:i+seq_length]
    _y=y[i+seq_length]
    #     _y=Y[i+seq_length:i+seq_length+forecastDays]
    print(_x,"->",_y)
    dataX.append(_x)
    dataY.append(_y)

[[  0.           4.          53.           0.05964912]
 [  0.           5.          53.           0.07192982]
 [  0.           6.          53.           0.09473684]
 [  0.           0.           1.           0.07192982]
 [  0.           1.           1.           0.06140351]
 [  0.           2.           1.           0.07719298]
 [  0.           3.           1.           0.0877193 ]] -> [ 0.07368421]
[[  0.           5.          53.           0.07192982]
 [  0.           6.          53.           0.09473684]
 [  0.           0.           1.           0.07192982]
 [  0.           1.           1.           0.06140351]
 [  0.           2.           1.           0.07719298]
 [  0.           3.           1.           0.0877193 ]
 [  0.           4.           1.           0.07368421]] -> [ 0.07368421]
[[  0.           6.          53.           0.09473684]
 [  0.           0.           1.           0.07192982]
 [  0.           1.           1.           0.06140351]
 [  0.           2.          

 [ 0.          6.          4.          0.08596491]] -> [ 0.07719298]
[[ 0.          1.          4.          0.06666667]
 [ 0.          2.          4.          0.09649123]
 [ 0.          3.          4.          0.08596491]
 [ 0.          4.          4.          0.0754386 ]
 [ 0.          5.          4.          0.08596491]
 [ 0.          6.          4.          0.08596491]
 [ 0.          0.          5.          0.07719298]] -> [ 0.06842105]
[[ 0.          2.          4.          0.09649123]
 [ 0.          3.          4.          0.08596491]
 [ 0.          4.          4.          0.0754386 ]
 [ 0.          5.          4.          0.08596491]
 [ 0.          6.          4.          0.08596491]
 [ 0.          0.          5.          0.07719298]
 [ 0.          1.          5.          0.06842105]] -> [ 0.09122807]
[[ 0.          3.          4.          0.08596491]
 [ 0.          4.          4.          0.0754386 ]
 [ 0.          5.          4.          0.08596491]
 [ 0.          6.          4

 [  3.00000000e+00   6.00000000e+00   4.20000000e+01   1.75438596e-02]] -> [ 0.02631579]
[[  3.00000000e+00   1.00000000e+00   4.20000000e+01   3.33333333e-02]
 [  3.00000000e+00   2.00000000e+00   4.20000000e+01   5.96491228e-02]
 [  3.00000000e+00   3.00000000e+00   4.20000000e+01   4.91228070e-02]
 [  3.00000000e+00   4.00000000e+00   4.20000000e+01   4.03508772e-02]
 [  3.00000000e+00   5.00000000e+00   4.20000000e+01   2.63157895e-02]
 [  3.00000000e+00   6.00000000e+00   4.20000000e+01   1.75438596e-02]
 [  3.00000000e+00   0.00000000e+00   4.30000000e+01   2.63157895e-02]] -> [ 0.01578947]
[[  3.00000000e+00   2.00000000e+00   4.20000000e+01   5.96491228e-02]
 [  3.00000000e+00   3.00000000e+00   4.20000000e+01   4.91228070e-02]
 [  3.00000000e+00   4.00000000e+00   4.20000000e+01   4.03508772e-02]
 [  3.00000000e+00   5.00000000e+00   4.20000000e+01   2.63157895e-02]
 [  3.00000000e+00   6.00000000e+00   4.20000000e+01   1.75438596e-02]
 [  3.00000000e+00   0.00000000e+00   4.3

## 2.4 train/test split

In [24]:
train_size = int(len(dataY) * 0.7)
test_size = len(dataY) - train_size
trainX, testX = np.array(dataX[0:train_size]), np.array(dataX[train_size:])
trainY, testY = np.array(dataY[0:train_size]), np.array(dataY[train_size:])

## 2.5 input place holders

X의 경우 input type과 [batch size, sequence length, input data dimension(feature+1))]

Y의 경우 input type과 [batch size, 원하는 output 의 개수(forecastDays)]

In [ ]:
X=tf.placeholder(tf.float32, [None, seq_length, data_dim])
Y=tf.placeholder(tf.float32, [None, forecastDays])

## 2.6 build LSTM network model

lstm network의 

    기본단위 cell, 
    
    사용 driver, 
    
    예측 y 산출방식, 
    
    loss 함수, 
    
    사용 optimizer 정하기

### lstm의 한 기본단위인 cell을 생성

cell의 결과값을 fully connected layer로 한 번 더 가공할 것이기 때문에 cell의 output dimension인 num_units=hidden_dim로 설정

In [ ]:
cell = tf.contrib.rnn.BasicLSTMCell(num_units=hidden_dim, state_is_tuple=True, activation=tf.tanh)

### Dynamic rnn이라는 driver를 가동

tf.dynamic_rnn의 input은 cell, input, input type

tf.dynamic_rnn의 output은 outputs와 states

In [ ]:
outputs, _states = tf.nn.dynamic_rnn(cell, X, dtype=tf.float32)

### 마지막 cell의 output을 이용하여 Y_pred 도출

outputs[:, -1]: cell의 outputs 중 마지막 하나만 이용(we use the last cell's output)

output_dim: fully connected의 최종출력개수는 output_dim(=forecastDays) 

activation_fn= None: 분류 문제가 아니라 회귀 문제이므로 activation_fn은 none

In [ ]:
Y_pred = tf.contrib.layers.fully_connected(outputs[:, -1], output_dim, activation_fn= None) 

### loss 정의

In [ ]:
loss = tf.reduce_sum(tf.square(Y_pred - Y))  # sum of the squares

### optimizer정의

In [ ]:
optimizer = tf.train.AdamOptimizer(learning_rate)

### loss를 줄이는 방향으로 train

In [ ]:
train = optimizer.minimize(loss)

# 3. Model 평가 with RMSE

In [ ]:
denormalizedTestY=originalSales[train_size+seq_length:]
denormalizedTestY_feed=np.array([[i] for i in denormalizedTestY])

In [ ]:
targets = tf.placeholder(tf.float32, [None, 1])
predictions = tf.placeholder(tf.float32, [None, 1])
rmse = tf.sqrt(tf.reduce_mean(tf.square(targets - predictions)))

In [ ]:
def rootMeanSquaredError(a,b):
    sum=0
    for i in range(len(a)):
        sum=sum+(a[i]-b[i])**2
    return np.sqrt( sum/len(a))

## 2.5 Train and Test

In [ ]:
with tf.Session() as sess:
    #초기화
    init = tf.global_variables_initializer()
    sess.run(init)

    # Training step
    for i in range(iterations):
        _, step_loss = sess.run([train, loss], feed_dict={X: trainX, Y: trainY})
        print("[step: {}] loss: {}".format(i, step_loss))

    # Test step
    test_predict = minMaxDeNormalizer(sess.run(Y_pred, feed_dict={X: testX}),originalSales)
    rmse_val = sess.run(rmse, feed_dict={targets: denormalizedTestY_feed, predictions: test_predict})
    print("RMSE: {}".format(rmse_val))

    # Plot predictions
    plt.plot(denormalizedTestY_feed)
    plt.plot(test_predict)
    plt.xlabel("Time Period")
    plt.ylabel("Stock Price")
    plt.show()

In [ ]:
denormalizedTestPredictY=[item for sublist in test_predict for item in sublist]

In [ ]:
rootMeanSquaredError(test_predictY_CALC,denormalizedTestY)